services:
  api:
    image:  bellphegorr/factor-investing:api-latest
    ports:
      - "5000:5000"
    networks:
      - factor-investing-network
    depends_on:
      - database
  migrator:
    image: bellphegorr/factor-investing:migrator-latest
    depends_on:
      - database
    networks:
      - factor-investing-network
  database:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factor_investing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - factor-investing-network
    restart: on-failure
networks:
  factor-investing-network:
    driver: overlay
    attachable: true
volumes:
  postgres-data: