services:
  api:
    container_name: factor-investing-api
    build: 
      context: ./src/
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - nuget-packages:/root/.nuget/packages
    working_dir: /app
    networks:
      - factor-investing-network
    depends_on:
      - database
    restart: on-failure
  migrator:
    image: bellphegorr/factor-investing:migrator-latest
    networks:
      - factor-investing-network
    depends_on:
      - database
  database:
    container_name: factor-investing-database
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factor_investing
    ports:
      - "5432:5432"
    networks:
      - factor-investing-network
    restart: on-failure
networks:
  factor-investing-network:
volumes:
  nuget-packages:
  postgres-data: