services:
  api:
    container_name: factor-investing-api
    build:
      context: ./src/
      target: final
      args:
        - CONFIGURATION=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - factor-investing-network
    depends_on:
      - database
  database:
    container_name: factor-investing-database
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factor_investing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - factor-investing-network
    restart: on-failure
networks:
  factor-investing-network:
volumes:
  postgres-data: