services:
  api:
    container_name: factor-investing-api
    build: 
      context: ./src/
      target: final
    ports:
      - "5000:5000"
    networks:
      - factor-investing-network
    depends_on:
      - database
    restart: on-failure
  dev:
    container_name: factor-investing-api-dev
    build: 
      context: ./src/
      target: dev
    ports:
      - "5001:5000"
    volumes:
      - ./src:/src
      - nuget-packages:/root/.nuget/packages
    networks:
      - factor-investing-network
    depends_on:
      - database
    restart: on-failure
  database:
    container_name: factor-investing-database
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factor_investing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - factor-investing-network
    restart: on-failure
networks:
  factor-investing-network:
volumes:
  nuget-packages:
  postgres-data: