services:
  api:
    image:  factor-investing-api
    container_name: factor-investing-api
    build: 
      context: ./src/
      target: final
      args:
        - CONFIGURATION=Release
    ports:
      - "5000:5000"
    networks:
      - factor-investing-network
    depends_on:
      - database
    restart: on-failure
  database:
    container_name: factor-investing-database
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factor_investing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - factor-investing-network
    restart: on-failure
  migrator:
    container_name: factor-investing-migrator
    build:
      context: ./src/
      target: migration
    depends_on:
      - database
    networks:
      - factor-investing-network
networks:
  factor-investing-network:
    # driver: overlay #test swarm
    # attachable: true #test swarm
volumes:
  postgres-data: